import { prisma } from "../prisma";
import { computeGovernanceScore } from "../actions/governance";

export async function getEnvironmentalFeatures(deptId: string, periodDays: number = 90) {
  const periodStart = new Date();
  periodStart.setDate(periodStart.getDate() - periodDays);

  const prevPeriodStart = new Date(periodStart);
  prevPeriodStart.setDate(prevPeriodStart.getDate() - periodDays);

  // 1. Total CO2 for current period
  const currentTxns = await prisma.carbonTransaction.findMany({
    where: {
      departmentId: deptId,
      date: { gte: periodStart },
    },
  });
  const totalCO2 = currentTxns.reduce((sum, tx) => sum + tx.co2Kg, 0);

  // 2. Previous period CO2 (for trend)
  const prevTxns = await prisma.carbonTransaction.findMany({
    where: {
      departmentId: deptId,
      date: { gte: prevPeriodStart, lt: periodStart },
    },
  });
  const prevTotalCO2 = prevTxns.reduce((sum, tx) => sum + tx.co2Kg, 0);
  const co2Trend = prevTotalCO2 === 0 ? 0 : (totalCO2 - prevTotalCO2) / prevTotalCO2;

  // 3. Goals metrics
  const onTrackGoals = await prisma.environmentalGoal.count({
    where: { departmentId: deptId, status: "ON_TRACK" },
  });
  const completedGoals = await prisma.environmentalGoal.count({
    where: { departmentId: deptId, status: "COMPLETED" },
  });

  // 4. Employee counts (for intensity)
  const employeeCount = await prisma.employee.count({
    where: { departmentId: deptId },
  });
  const emissionIntensity = employeeCount > 0 ? totalCO2 / employeeCount : totalCO2;

  // 5. Auto generation ratio
  const autoGeneratedTxns = currentTxns.filter((tx) => tx.autoGenerated).length;
  const autoRatio = currentTxns.length > 0 ? autoGeneratedTxns / currentTxns.length : 0;

  return {
    totalCO2,
    co2Trend,
    goalsOnTrack: onTrackGoals,
    goalsCompleted: completedGoals,
    emissionIntensity,
    autoRatio,
  };
}

export async function getSocialFeatures(deptId: string, periodDays: number = 90) {
  const periodStart = new Date();
  periodStart.setDate(periodStart.getDate() - periodDays);

  const employees = await prisma.employee.findMany({
    where: { departmentId: deptId },
    include: {
      participations: {
        where: { createdAt: { gte: periodStart } },
      },
      trainingRecords: {
        where: { createdAt: { gte: periodStart } },
      },
      challengeParticipations: {
        where: { createdAt: { gte: periodStart } },
      },
    },
  });

  const numEmployees = employees.length || 1; // Prevent division by zero

  // 1. CSR Participation rate
  const totalParticipations = employees.reduce((sum, emp) => sum + emp.participations.length, 0);
  const participationRate = totalParticipations / numEmployees;

  // 2. Training Completion rate
  let totalTrainings = 0;
  let completedTrainings = 0;
  for (const emp of employees) {
    totalTrainings += emp.trainingRecords.length;
    completedTrainings += emp.trainingRecords.filter(t => t.completed).length;
  }
  const trainingCompletionRate = totalTrainings > 0 ? completedTrainings / totalTrainings : 0;

  // 3. Challenge participation rate
  const totalChallengeParts = employees.reduce((sum, emp) => sum + emp.challengeParticipations.length, 0);
  const challengeRate = totalChallengeParts / numEmployees;

  // 4. Diversity Index (simple heuristic: 1.0 minus absolute difference from 50/50 gender split)
  // Assumes gender field has values like "Male", "Female", etc.
  const males = employees.filter(e => e.gender?.toLowerCase() === "male").length;
  const females = employees.filter(e => e.gender?.toLowerCase() === "female").length;
  const specifiedGenders = males + females;
  
  let diversityIndex = 1.0;
  if (specifiedGenders > 0) {
    const ratio = females / specifiedGenders;
    // 0.5 is perfectly diverse. Abs difference from 0.5.
    const deviation = Math.abs(ratio - 0.5); 
    // diversityIndex is 1.0 when perfectly diverse, goes down to 0.0 when completely skewed.
    diversityIndex = 1.0 - (deviation * 2); 
  }

  return {
    participationRate,
    diversityIndex,
    trainingCompletionRate,
    challengeRate,
  };
}

// Re-export governance score for convenience in scoring actions
export { computeGovernanceScore };
