"use server";

// Environmental Module — Dashboard Data Server Action
// Owner: Team A (Environmental)
//
// Single server action that returns all KPIs + chart data in one round-trip,
// using Promise.all to maximise concurrency.

import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth-utils";
import type { CarbonTransaction, EmissionFactor } from "@/lib/generated/prisma/client";

export interface EnvironmentalKPIs {
  totalCO2ThisMonth: number;
  totalCO2LastMonth: number;
  co2TrendPct: number | null;     // null if no last-month data
  envScore: number;
  isFallback: boolean;
  goalsOnTrack: number;
  totalActiveGoals: number;
  emissionIntensity: number;      // kg CO₂ / employee this month
  emissionIntensityLastMonth: number;
}

export interface RecentTransaction {
  id: string;
  date: Date;
  departmentName: string;
  sourceType: string;
  co2Kg: number;
  autoGenerated: boolean;
  factorActivity: string;
}

export interface GoalSummary {
  id: string;
  name: string;
  departmentName: string;
  currentCO2Kg: number;
  targetCO2Kg: number;
  progressPct: number;
  status: string;
  deadline: Date;
}

export interface TrendPoint {
  month: string;
  co2Kg: number;
}

export interface DeptBreakdown {
  departmentId: string;
  departmentName: string;
  totalCO2Kg: number;
}

export interface EnvironmentalDashboardData {
  kpis: EnvironmentalKPIs;
  trendData: TrendPoint[];
  deptBreakdown: DeptBreakdown[];
  recentTransactions: RecentTransaction[];
  goalsSummary: GoalSummary[];
}

export async function getEnvironmentalDashboardData(): Promise<EnvironmentalDashboardData> {
  await requireAuth();

  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const startOfLastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const endOfLastMonth = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59);

  // ── All queries run concurrently ──────────────────────────────────────────
  const [
    thisMonthAgg,
    lastMonthAgg,
    departmentScore,
    goals,
    employeeCount,
    recentTx,
    departments,
  ] = await Promise.all([
    prisma.carbonTransaction.aggregate({
      where: { date: { gte: startOfMonth } },
      _sum: { co2Kg: true },
    }),
    prisma.carbonTransaction.aggregate({
      where: { date: { gte: startOfLastMonth, lte: endOfLastMonth } },
      _sum: { co2Kg: true },
    }),
    // Org-level score: average across all department scores
    prisma.departmentScore.findMany({ select: { environmental: true, isFallback: true } }),
    prisma.environmentalGoal.findMany({
      where: { status: { not: "COMPLETED" } },
      include: { department: { select: { name: true } } },
      orderBy: [{ status: "asc" }, { deadline: "asc" }],
      take: 8,
    }),
    prisma.employee.count(),
    prisma.carbonTransaction.findMany({
      take: 10,
      orderBy: { date: "desc" },
      include: {
        department: { select: { name: true } },
        emissionFactor: { select: { activity: true } },
      },
    }),
    prisma.department.findMany({
      where: { status: "ACTIVE" },
      include: {
        carbonTransactions: {
          where: { date: { gte: startOfMonth } },
          select: { co2Kg: true },
        },
      },
    }),
  ]);

  // ── KPIs ─────────────────────────────────────────────────────────────────
  const totalCO2ThisMonth = Math.round((thisMonthAgg._sum.co2Kg ?? 0) * 10) / 10;
  const totalCO2LastMonth = Math.round((lastMonthAgg._sum.co2Kg ?? 0) * 10) / 10;
  const co2TrendPct =
    totalCO2LastMonth > 0
      ? Math.round(((totalCO2ThisMonth - totalCO2LastMonth) / totalCO2LastMonth) * 100 * 10) / 10
      : null;

  const avgEnvScore =
    departmentScore.length > 0
      ? Math.round(
          departmentScore.reduce((s, d) => s + d.environmental, 0) /
            departmentScore.length
        )
      : 0;
  const anyFallback = departmentScore.some((d) => d.isFallback);

  const goalsOnTrack = goals.filter(
    (g) => g.status === "ON_TRACK" || g.status === "COMPLETED"
  ).length;
  const totalActiveGoals = goals.length;

  const emp = Math.max(employeeCount, 1);
  const emissionIntensity = Math.round((totalCO2ThisMonth / emp) * 100) / 100;
  const emissionIntensityLastMonth = Math.round((totalCO2LastMonth / emp) * 100) / 100;

  // ── Trend data: last 12 months ────────────────────────────────────────────
  const trendData: TrendPoint[] = [];
  for (let i = 11; i >= 0; i--) {
    const start = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const end = new Date(now.getFullYear(), now.getMonth() - i + 1, 0, 23, 59, 59);
    const agg = await prisma.carbonTransaction.aggregate({
      where: { date: { gte: start, lte: end } },
      _sum: { co2Kg: true },
    });
    trendData.push({
      month: `${start.getFullYear()}-${String(start.getMonth() + 1).padStart(2, "0")}`,
      co2Kg: Math.round((agg._sum.co2Kg ?? 0) * 10) / 10,
    });
  }

  // ── Dept breakdown (current month) ───────────────────────────────────────
  const deptBreakdown: DeptBreakdown[] = departments
    .map((d) => ({
      departmentId: d.id,
      departmentName: d.name,
      totalCO2Kg:
        Math.round(
          d.carbonTransactions.reduce((acc, t) => acc + t.co2Kg, 0) * 10
        ) / 10,
    }))
    .filter((d) => d.totalCO2Kg > 0)
    .sort((a, b) => b.totalCO2Kg - a.totalCO2Kg);

  // ── Recent transactions ───────────────────────────────────────────────────
  const recentTransactions: RecentTransaction[] = recentTx.map((t) => ({
    id: t.id,
    date: t.date,
    departmentName: t.department.name,
    sourceType: t.sourceType,
    co2Kg: t.co2Kg,
    autoGenerated: t.autoGenerated,
    factorActivity: t.emissionFactor.activity,
  }));

  // ── Goals summary ─────────────────────────────────────────────────────────
  const goalsSummary: GoalSummary[] = goals.map((g) => ({
    id: g.id,
    name: g.name,
    departmentName: g.department.name,
    currentCO2Kg: g.currentCO2Kg,
    targetCO2Kg: g.targetCO2Kg,
    progressPct:
      g.targetCO2Kg > 0
        ? Math.round((g.currentCO2Kg / g.targetCO2Kg) * 100)
        : 0,
    status: g.status,
    deadline: g.deadline,
  }));

  return {
    kpis: {
      totalCO2ThisMonth,
      totalCO2LastMonth,
      co2TrendPct,
      envScore: avgEnvScore,
      isFallback: anyFallback,
      goalsOnTrack,
      totalActiveGoals,
      emissionIntensity,
      emissionIntensityLastMonth,
    },
    trendData,
    deptBreakdown,
    recentTransactions,
    goalsSummary,
  };
}
