"use server";

// Environmental Module — Environmental Score Computation
// Owner: Team A (Environmental)
//
// Architecture:
//   1. Extract feature vector from Prisma (pure function)
//   2. Try ML microservice at localhost:8000 (2s timeout)
//   3. On failure → deterministic fallback formula
//   4. Write to DepartmentScore + log ScoreFeedback for future retraining
//   5. Recompute DepartmentScore.total using ESGConfig weights

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

// Baseline for fallback formula: kg CO₂ / employee / 30 days
// A department at this level scores ~50/100.
const BASELINE_INTENSITY_KG = 50;

// ─── Feature Extraction ───────────────────────────────────────────────────────

export interface EnvironmentalFeatures {
  co2ThisPeriod: number;
  co2LastPeriod: number;
  co2TrendDelta: number;
  goalsOnTrackPct: number;
  emissionIntensity: number;
  autoManualRatio: number;
  employeeCount: number;
}

/**
 * Extract the feature vector for a department over the last 30 days.
 * Pure: reads only, no writes.
 */
export async function extractEnvironmentalFeatures(
  departmentId: string
): Promise<EnvironmentalFeatures> {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const sixtyDaysAgo = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);

  const [
    thisAgg,
    lastAgg,
    totalTxCount,
    autoTxCount,
    goals,
    employeeCount,
  ] = await Promise.all([
    // CO₂ this 30-day period
    prisma.carbonTransaction.aggregate({
      where: { departmentId, date: { gte: thirtyDaysAgo } },
      _sum: { co2Kg: true },
    }),
    // CO₂ prior 30-day period (30–60 days ago)
    prisma.carbonTransaction.aggregate({
      where: { departmentId, date: { gte: sixtyDaysAgo, lt: thirtyDaysAgo } },
      _sum: { co2Kg: true },
    }),
    // Total transactions in last 30 days
    prisma.carbonTransaction.count({
      where: { departmentId, date: { gte: thirtyDaysAgo } },
    }),
    // Auto-generated transactions in last 30 days
    prisma.carbonTransaction.count({
      where: { departmentId, date: { gte: thirtyDaysAgo }, autoGenerated: true },
    }),
    // Goal statuses for this department
    prisma.environmentalGoal.findMany({
      where: { departmentId },
      select: { status: true },
    }),
    // Employee headcount
    prisma.employee.count({ where: { departmentId } }),
  ]);

  const co2ThisPeriod = thisAgg._sum.co2Kg ?? 0;
  const co2LastPeriod = lastAgg._sum.co2Kg ?? 0;
  const co2TrendDelta = co2ThisPeriod - co2LastPeriod;
  const emp = Math.max(employeeCount, 1); // avoid div/0
  const emissionIntensity = co2ThisPeriod / emp;
  const autoManualRatio = totalTxCount > 0 ? autoTxCount / totalTxCount : 0;

  const activeGoals = goals.filter(
    (g) => g.status !== "COMPLETED" && g.status !== "ACTIVE" ? true : true
  );
  const onTrackGoals = goals.filter(
    (g) => g.status === "ON_TRACK" || g.status === "COMPLETED"
  );
  const goalsOnTrackPct =
    goals.length > 0 ? onTrackGoals.length / goals.length : 0;

  return {
    co2ThisPeriod,
    co2LastPeriod,
    co2TrendDelta,
    goalsOnTrackPct,
    emissionIntensity,
    autoManualRatio,
    employeeCount: emp,
  };
}

// ─── Fallback Formula ─────────────────────────────────────────────────────────

/**
 * Deterministic fallback score (0–100).
 * Used when the ML service is unavailable. This is the same heuristic used to
 * generate training labels for the ML model — so the two are consistent.
 *
 * Components:
 *   - Base: 100 - intensity penalty (max 80 pts off)
 *   - Bonus: goal completion ratio (up to +20)
 *   - Penalty: rising trend vs last period (up to -15)
 */
export async function computeEnvironmentalScoreFallback(
  features: EnvironmentalFeatures
): Promise<number> {
  const {
    emissionIntensity,
    goalsOnTrackPct,
    co2TrendDelta,
    co2LastPeriod,
  } = features;

  const intensityRatio = emissionIntensity / BASELINE_INTENSITY_KG;
  const intensityPenalty = Math.min(intensityRatio * 60, 80);

  const goalBonus = goalsOnTrackPct * 20;

  const trendPenalty =
    co2LastPeriod > 0
      ? Math.max(0, (co2TrendDelta / co2LastPeriod) * 15)
      : 0;

  const raw = 100 - intensityPenalty + goalBonus - trendPenalty;
  return Math.max(0, Math.min(100, Math.round(raw)));
}

// ─── ML Service Call ──────────────────────────────────────────────────────────

async function callMLService(
  features: EnvironmentalFeatures
): Promise<number | null> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2000); // 2s timeout

    const res = await fetch("http://localhost:8000/score/environmental", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(features),
      signal: controller.signal,
    });

    clearTimeout(timeout);
    if (!res.ok) return null;

    const json = (await res.json()) as { score?: number };
    const score = json.score;
    if (typeof score !== "number" || score < 0 || score > 100) return null;
    return Math.round(score);
  } catch {
    // AbortError (timeout) or network error — fall back silently
    return null;
  }
}

// ─── Main Recompute ───────────────────────────────────────────────────────────

/**
 * Recompute the Environmental Score for a department.
 * Called after every Carbon Transaction write.
 *
 * Flow:
 *  1. Extract features
 *  2. Try ML service (2s timeout)
 *  3. Fallback if ML unavailable
 *  4. Upsert DepartmentScore.environmental + recompute total
 *  5. Log ScoreFeedback for future retraining
 */
export async function recomputeEnvironmentalScore(
  departmentId: string
): Promise<void> {
  const features = await extractEnvironmentalFeatures(departmentId);

  const mlScore = await callMLService(features);
  const isFallback = mlScore === null;
  const envScore = isFallback
    ? await computeEnvironmentalScoreFallback(features)
    : mlScore!;

  // Read ESG weights (use defaults if no config row yet)
  const config = await prisma.eSGConfig.findFirst();
  const envWeight = config?.envWeight ?? 0.4;
  const socialWeight = config?.socialWeight ?? 0.3;
  const govWeight = config?.govWeight ?? 0.3;

  // Get existing scores to preserve social + governance values
  const existing = await prisma.departmentScore.findUnique({
    where: { departmentId },
  });
  const social = existing?.social ?? 0;
  const governance = existing?.governance ?? 0;
  const total = Math.round(
    envScore * envWeight + social * socialWeight + governance * govWeight
  );

  // Upsert DepartmentScore
  await prisma.departmentScore.upsert({
    where: { departmentId },
    create: {
      departmentId,
      environmental: envScore,
      social,
      governance,
      total,
      isFallback,
    },
    update: {
      environmental: envScore,
      total,
      isFallback,
      // updatedAt is managed by @updatedAt — no manual set needed
    },
  });

  // Log ScoreFeedback for ML retraining pipeline
  await prisma.scoreFeedback.create({
    data: {
      departmentId,
      scoreType: "ENVIRONMENTAL",
      features: JSON.stringify(features),
      predictedScore: envScore,
      correctedScore: null,
    },
  });

  revalidatePath("/environmental");
  revalidatePath("/dashboard");
}
