import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getCustomReportData } from "@/lib/actions/reports";
import { ReportFilters } from "@/components/reports/ReportFilters";
import { ExportButtons } from "@/components/reports/ExportButtons";
import { KpiCard } from "@/components/dashboard/KpiCard";
import type { EnvironmentalReportData, SocialReportData, GovernanceReportData, EsgSummaryData } from "@/lib/actions/reports";

export const metadata = { title: "Custom Report — EcoSphere" };

export default async function CustomReportPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string>>;
}) {
  const session = await auth();
  if (!session?.user) redirect("/login");

  const params = await searchParams;
  const filters = {
    departmentId: params.dept,
    fromDate: params.from ? new Date(params.from) : undefined,
    toDate: params.to ? new Date(params.to) : undefined,
    module: params.module,
  };

  const [data, departments] = await Promise.all([
    getCustomReportData(filters as any),
    prisma.department.findMany({
      where: { status: "ACTIVE" },
      select: { id: true, name: true, code: true },
    }),
  ]);

  const env = data.environmental as EnvironmentalReportData | undefined;
  const soc = data.social as SocialReportData | undefined;
  const gov = data.governance as GovernanceReportData | undefined;
  const gam = data.gamification as EsgSummaryData | undefined;

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1
            className="text-3xl font-bold text-foreground"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Custom Report Builder
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Build and export reports by combining data across multiple ESG modules.
          </p>
        </div>
        <ExportButtons reportType="custom" filters={params} />
      </div>

      <ReportFilters departments={departments} showModule />

      {/* Dynamic Sections */}
      {gam && (
        <section className="space-y-4">
          <h2 className="text-xl font-bold text-foreground" style={{ fontFamily: "var(--font-heading)" }}>
            Overall ESG Performance
          </h2>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <KpiCard title="Overall Score" value={gam.summary.overallESGScore} isScore accentColor="var(--chart-1)" />
            <KpiCard title="Environmental" value={gam.summary.envScore} isScore accentColor="var(--esg-env)" />
            <KpiCard title="Social" value={gam.summary.socialScore} isScore accentColor="var(--esg-social)" />
            <KpiCard title="Governance" value={gam.summary.govScore} isScore accentColor="var(--esg-gov)" />
          </div>
        </section>
      )}

      {env && (
        <section className="space-y-4 pt-4 border-t border-border">
          <h2 className="text-xl font-bold text-foreground" style={{ fontFamily: "var(--font-heading)" }}>
            Environmental Highlights
          </h2>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <KpiCard title="Total CO₂" value={env.summary.totalCO2Kg} subtitle="kg CO₂e" accentColor="var(--esg-env)" />
            <KpiCard title="Tx Count" value={env.summary.txCount} subtitle="Records logged" accentColor="var(--chart-2)" />
            <KpiCard title="Goals On-Track" value={`${Math.round(env.summary.goalsOnTrackPct)}%`} accentColor="var(--chart-1)" />
            <KpiCard title="Auto-Generated" value={`${Math.round(env.summary.autoGeneratedPct)}%`} accentColor="var(--chart-5)" />
          </div>
        </section>
      )}

      {soc && (
        <section className="space-y-4 pt-4 border-t border-border">
          <h2 className="text-xl font-bold text-foreground" style={{ fontFamily: "var(--font-heading)" }}>
            Social Highlights
          </h2>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <KpiCard title="CSR Activities" value={soc.summary.totalActivities} accentColor="var(--esg-social)" />
            <KpiCard title="Participations" value={soc.summary.totalParticipations} accentColor="var(--chart-2)" />
            <KpiCard title="Approval Rate" value={`${Math.round(soc.summary.approvalRate)}%`} accentColor="var(--chart-1)" />
            <KpiCard title="Training Completed" value={`${Math.round(soc.summary.trainingCompletionRate)}%`} accentColor="var(--chart-5)" />
          </div>
        </section>
      )}

      {gov && (
        <section className="space-y-4 pt-4 border-t border-border">
          <h2 className="text-xl font-bold text-foreground" style={{ fontFamily: "var(--font-heading)" }}>
            Governance Highlights
          </h2>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <KpiCard title="Policy Ack. Rate" value={`${Math.round(gov.summary.policyAckRate)}%`} accentColor="var(--esg-gov)" />
            <KpiCard title="Open Issues" value={gov.summary.openIssues} accentColor={gov.summary.openIssues > 0 ? "var(--destructive)" : "var(--chart-1)"} />
            <KpiCard title="Overdue Issues" value={gov.summary.overdueIssues} accentColor={gov.summary.overdueIssues > 0 ? "var(--destructive)" : "var(--chart-1)"} />
            <KpiCard title="Audits Completed" value={gov.summary.auditsCompleted} accentColor="var(--chart-5)" />
          </div>
        </section>
      )}
    </div>
  );
}
