import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getEnvironmentalReportData } from "@/lib/actions/reports";
import { ReportFilters } from "@/components/reports/ReportFilters";
import { KpiCard } from "@/components/dashboard/KpiCard";
import { EnvironmentalReportCharts } from "@/components/reports/EnvironmentalReportView";
import { ExportButtons } from "@/components/reports/ExportButtons";
import { Badge } from "@/components/ui/badge";
import { formatCO2, daysUntil } from "@/lib/gamification-utils";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Environmental Report — EcoSphere",
};

export default async function EnvironmentalReportPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string>>;
}) {
  const session = await auth();
  if (!session?.user) redirect("/login");

  const params = await searchParams;
  const filters = {
    departmentId: params.dept,
    fromDate: params.from ? new Date(params.from) : undefined,
    toDate: params.to ? new Date(params.to) : undefined,
  };

  const [data, departments] = await Promise.all([
    getEnvironmentalReportData(filters),
    prisma.department.findMany({
      where: { status: "ACTIVE" },
      select: { id: true, name: true, code: true },
    }),
  ]);

  const STATUS_COLORS: Record<string, string> = {
    ON_TRACK: "bg-chart-1/15 text-chart-1 border-chart-1/25",
    AT_RISK: "bg-chart-4/15 text-chart-4 border-chart-4/25",
    COMPLETED: "bg-chart-2/15 text-chart-2 border-chart-2/25",
    MISSED: "bg-destructive/15 text-destructive border-destructive/25",
  };

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1
            className="text-3xl font-bold text-foreground"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Environmental Report
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Carbon emissions, energy usage, and environmental goals.
          </p>
        </div>
        <ExportButtons reportType="environmental" filters={params} />
      </div>

      <ReportFilters departments={departments} />

      {/* KPI row */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <KpiCard
          title="Total CO₂e"
          value={formatCO2(data.summary.totalCO2Kg)}
          subtitle={`${data.summary.txCount} transactions`}
          accentColor="var(--esg-env)"
        />
        <KpiCard
          title="Auto-calculated"
          value={`${Math.round(data.summary.autoGeneratedPct)}%`}
          subtitle="Of all transactions"
          accentColor="var(--chart-2)"
        />
        <KpiCard
          title="Goals on-track"
          value={`${Math.round(data.summary.goalsOnTrackPct)}%`}
          subtitle={`${data.goals.length} total goals`}
          isScore
          accentColor="var(--chart-1)"
        />
        <KpiCard
          title="Top emitter"
          value={data.byDept[0]?.name ?? "N/A"}
          subtitle={data.byDept[0] ? formatCO2(data.byDept[0].co2Kg) : ""}
          accentColor="var(--destructive)"
        />
      </div>

      {/* Charts */}
      <EnvironmentalReportCharts
        byMonth={data.byMonth}
        bySource={data.bySource}
        byDept={data.byDept}
      />

      {/* Goals table */}
      <div className="rounded-xl border border-border overflow-hidden">
        <div className="px-5 py-3 bg-muted/40 border-b border-border">
          <h3
            className="text-sm font-semibold text-foreground"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Environmental Goals
          </h3>
        </div>
        <div className="divide-y divide-border/50">
          {data.goals.map((goal) => {
            const progress =
              goal.targetCO2Kg > 0
                ? Math.min(100, (goal.currentCO2Kg / goal.targetCO2Kg) * 100)
                : 0;
            const days = daysUntil(goal.deadline);
            return (
              <div
                key={goal.id}
                className="px-5 py-3 flex items-center gap-4 hover:bg-accent/30 transition-colors"
              >
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-foreground">{goal.name}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {goal.department.name} ·{" "}
                    <span style={{ fontFamily: "var(--font-mono)" }}>
                      {formatCO2(goal.currentCO2Kg)} / {formatCO2(goal.targetCO2Kg)}
                    </span>
                  </p>
                </div>
                {/* Mini progress bar */}
                <div className="w-24 h-1.5 rounded-full bg-muted overflow-hidden shrink-0">
                  <div
                    className="h-full rounded-full bg-chart-1 transition-all"
                    style={{ width: `${progress}%` }}
                  />
                </div>
                <span
                  className="text-xs text-muted-foreground shrink-0 w-16 text-right"
                  style={{ fontFamily: "var(--font-mono)" }}
                >
                  {Math.round(progress)}%
                </span>
                <Badge
                  variant="outline"
                  className={cn(
                    "text-xs border shrink-0",
                    STATUS_COLORS[goal.status] ?? "text-muted-foreground"
                  )}
                >
                  {goal.status.replace("_", " ")}
                </Badge>
                <span
                  className={cn(
                    "text-xs shrink-0 w-20 text-right",
                    days < 0 ? "text-destructive" : "text-muted-foreground"
                  )}
                >
                  {days < 0 ? `${Math.abs(days)}d overdue` : `${days}d left`}
                </span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
