"use client";

// Carbon Transactions Table — with filter bar, CSV export, Auto/Manual badges,
// and admin ERP Simulation button.

import { useState, useTransition } from "react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Trash2, Factory, Download, RefreshCw, AlertTriangle } from "lucide-react";
import { LogCarbonDialog } from "@/components/environmental/LogCarbonDialog";
import {
  deleteCarbonTransaction,
  simulateAutoEmission,
  type CarbonTransactionWithRefs,
} from "@/lib/actions/environmental/carbon-transactions";
import type { EmissionFactor, Department } from "@/lib/generated/prisma/client";
import { cn } from "@/lib/utils";

const SOURCE_LABELS: Record<string, string> = {
  PURCHASE: "Purchase",
  MANUFACTURING: "Manufacturing",
  EXPENSE: "Expense",
  FLEET: "Fleet",
  MANUAL: "Manual",
};

const SOURCE_COLORS: Record<string, string> = {
  PURCHASE: "bg-chart-2/15 text-chart-2 border-chart-2/25",
  MANUFACTURING: "bg-chart-5/15 text-chart-5 border-chart-5/25",
  EXPENSE: "bg-chart-3/15 text-chart-3 border-chart-3/25",
  FLEET: "bg-chart-4/15 text-chart-4 border-chart-4/25",
  MANUAL: "bg-muted text-muted-foreground border-border",
};

interface Props {
  transactions: CarbonTransactionWithRefs[];
  departments: Pick<Department, "id" | "name">[];
  emissionFactors: EmissionFactor[];
  isAdmin: boolean;
  autoEmissionEnabled: boolean;
  lockedDepartmentId?: string;
}

export function CarbonTransactionsTable({
  transactions,
  departments,
  emissionFactors,
  isAdmin,
  autoEmissionEnabled,
  lockedDepartmentId,
}: Props) {
  const [dialogOpen, setDialogOpen] = useState(false);
  const [filterDept, setFilterDept] = useState("all");
  const [filterSource, setFilterSource] = useState("all");
  const [filterDateFrom, setFilterDateFrom] = useState("");
  const [filterDateTo, setFilterDateTo] = useState("");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [simulateTarget, setSimulateTarget] = useState("");
  const [isPending, startTransition] = useTransition();

  // Client-side filter
  const filtered = transactions.filter((t) => {
    if (filterDept !== "all" && t.departmentId !== filterDept) return false;
    if (filterSource !== "all" && t.sourceType !== filterSource) return false;
    if (filterDateFrom && new Date(t.date) < new Date(filterDateFrom)) return false;
    if (filterDateTo && new Date(t.date) > new Date(filterDateTo)) return false;
    return true;
  });

  const handleDelete = (id: string) => {
    if (!confirm("Delete this transaction? This will update goal progress and scores.")) return;
    setErrorMsg(null);
    startTransition(async () => {
      const result = await deleteCarbonTransaction(id);
      if (!result.success) setErrorMsg(result.error);
    });
  };

  const handleSimulate = () => {
    const deptId = simulateTarget || departments[0]?.id;
    if (!deptId) return;
    startTransition(async () => {
      const result = await simulateAutoEmission(deptId);
      if (!result.success) setErrorMsg(result.error);
    });
  };

  // CSV export — client-side
  const exportCSV = () => {
    const header = "Date,Department,Source,Factor,Quantity,CO₂ (kg),Auto,Notes\n";
    const rows = filtered.map((t) =>
      [
        new Date(t.date).toISOString().split("T")[0],
        `"${t.department.name}"`,
        t.sourceType,
        `"${t.emissionFactor.activity}"`,
        t.quantity,
        t.co2Kg,
        t.autoGenerated ? "Auto" : "Manual",
        `"${t.notes ?? ""}"`,
      ].join(",")
    );
    const csv = header + rows.join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `carbon-transactions-${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Toolbar */}
      <div className="flex flex-wrap items-center gap-3 justify-between">
        <div className="flex flex-wrap items-center gap-2">
          {/* Dept filter */}
          <Select value={filterDept} onValueChange={(v) => setFilterDept(v ?? "all")}>
            <SelectTrigger className="h-8 w-44 text-xs">
              <SelectValue placeholder="All departments" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All departments</SelectItem>
              {departments.map((d) => (
                <SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>

          {/* Source filter */}
          <Select value={filterSource} onValueChange={(v) => setFilterSource(v ?? "all")}>
            <SelectTrigger className="h-8 w-40 text-xs">
              <SelectValue placeholder="All sources" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All sources</SelectItem>
              {Object.entries(SOURCE_LABELS).map(([v, l]) => (
                <SelectItem key={v} value={v}>{l}</SelectItem>
              ))}
            </SelectContent>
          </Select>

          {/* Date range */}
          <Input
            type="date"
            className="h-8 w-36 text-xs"
            value={filterDateFrom}
            onChange={(e) => setFilterDateFrom(e.target.value)}
            aria-label="From date"
          />
          <span className="text-xs text-muted-foreground">to</span>
          <Input
            type="date"
            className="h-8 w-36 text-xs"
            value={filterDateTo}
            onChange={(e) => setFilterDateTo(e.target.value)}
            aria-label="To date"
          />
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={exportCSV} className="h-8 gap-1.5 text-xs">
            <Download className="size-3.5" />
            Export CSV
          </Button>
          <Button size="sm" className="h-8 gap-1.5 text-xs" onClick={() => setDialogOpen(true)}>
            + Log Carbon Data
          </Button>
        </div>
      </div>

      {/* Admin: ERP simulation */}
      {isAdmin && autoEmissionEnabled && (
        <div className="flex items-center gap-3 rounded-lg border border-[--esg-social]/30 bg-[--esg-social]/5 px-4 py-3">
          <RefreshCw className="size-4 text-[--esg-social] shrink-0" />
          <p className="text-sm text-muted-foreground flex-1">
            Auto-emission calculation is <strong className="text-foreground">enabled</strong>.
            Simulate an ERP sync to generate automatic transactions.
          </p>
          <Select value={simulateTarget} onValueChange={(v) => setSimulateTarget(v ?? "")}>
            <SelectTrigger className="h-8 w-40 text-xs">
              <SelectValue placeholder="Select dept…" />
            </SelectTrigger>
            <SelectContent>
              {departments.map((d) => (
                <SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button size="sm" variant="outline" className="h-8 text-xs shrink-0" onClick={handleSimulate} disabled={isPending}>
            {isPending ? "Simulating…" : "Simulate ERP Sync"}
          </Button>
        </div>
      )}

      {/* Error */}
      {errorMsg && (
        <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
          <AlertTriangle className="size-4 mt-0.5 shrink-0" />
          <span>{errorMsg}</span>
        </div>
      )}

      {/* Stats */}
      <p className="text-xs text-muted-foreground">
        {filtered.length} transaction{filtered.length !== 1 ? "s" : ""} ·{" "}
        <span className="font-mono text-[--esg-env]">
          {filtered.reduce((s, t) => s + t.co2Kg, 0).toFixed(2)} kg CO₂
        </span>{" "}
        total
      </p>

      {/* Empty */}
      {filtered.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-muted/20 py-12 gap-3 text-center">
          <Factory className="size-10 text-muted-foreground/40" />
          <p className="text-sm text-muted-foreground">
            No transactions match the current filters.
          </p>
        </div>
      ) : (
        <div className="rounded-lg border border-border overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/40 hover:bg-muted/40">
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground">Date</TableHead>
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground">Department</TableHead>
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground">Source</TableHead>
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground">Factor</TableHead>
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground text-right">Qty</TableHead>
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground text-right">CO₂ (kg)</TableHead>
                <TableHead className="text-xs uppercase tracking-wide text-muted-foreground">Type</TableHead>
                {isAdmin && <TableHead />}
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.map((t, idx) => (
                <TableRow
                  key={t.id}
                  className={cn("hover:bg-accent/50 transition-colors", idx % 2 === 1 && "bg-muted/20")}
                >
                  <TableCell className="text-xs text-muted-foreground font-mono">
                    {new Date(t.date).toLocaleDateString("en-IN")}
                  </TableCell>
                  <TableCell className="text-sm">{t.department.name}</TableCell>
                  <TableCell>
                    <Badge variant="outline" className={cn("text-xs", SOURCE_COLORS[t.sourceType])}>
                      {SOURCE_LABELS[t.sourceType]}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground max-w-[140px] truncate">
                    {t.emissionFactor.activity}
                  </TableCell>
                  <TableCell className="text-right font-mono text-xs">
                    {t.quantity} {t.emissionFactor.unit}
                  </TableCell>
                  <TableCell className="text-right">
                    <span className="font-mono text-sm font-medium text-[--esg-env]">
                      {t.co2Kg.toFixed(3)}
                    </span>
                  </TableCell>
                  <TableCell>
                    {t.autoGenerated ? (
                      <Badge variant="outline" className="text-[10px] bg-chart-2/10 text-chart-2 border-chart-2/25">
                        Auto
                      </Badge>
                    ) : (
                      <Badge variant="outline" className="text-[10px] text-muted-foreground">
                        Manual
                      </Badge>
                    )}
                  </TableCell>
                  {isAdmin && (
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 w-7 p-0 text-destructive hover:text-destructive hover:bg-destructive/10"
                        onClick={() => handleDelete(t.id)}
                        aria-label="Delete transaction"
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </TableCell>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      <LogCarbonDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        departments={departments}
        emissionFactors={emissionFactors}
        lockedDepartmentId={lockedDepartmentId}
      />
    </div>
  );
}
