"use server";

/**
 * Reports Data Fetchers
 * Server-side only — these power the 5 report pages and the export route.
 * All inputs are validated with Zod. Auth checked at start.
 */

import { requireAuth } from "@/lib/auth-utils";
import { prisma } from "@/lib/prisma";
import type { CustomReportFilters } from "@/lib/schemas/gamification";

// ─── Shared filter helpers ────────────────────────────────────────────────────

function dateRange(from?: Date, to?: Date) {
  const now = new Date();
  return {
    gte: from ?? new Date(now.getFullYear(), now.getMonth() - 11, 1),
    lte: to ?? now,
  };
}

// ─── Environmental Report ─────────────────────────────────────────────────────

export async function getEnvironmentalReportData(filters?: {
  departmentId?: string;
  fromDate?: Date;
  toDate?: Date;
}) {
  await requireAuth();

  const range = dateRange(filters?.fromDate, filters?.toDate);
  const deptFilter = filters?.departmentId
    ? { departmentId: filters.departmentId }
    : {};

  const [transactions, goals, emissionFactors, depts] = await Promise.all([
    prisma.carbonTransaction.findMany({
      where: { date: range, ...deptFilter },
      include: {
        department: { select: { name: true, code: true } },
        emissionFactor: { select: { activity: true, unit: true } },
      },
      orderBy: { date: "desc" },
    }),
    prisma.environmentalGoal.findMany({
      where: deptFilter,
      include: { department: { select: { name: true } } },
      orderBy: { deadline: "asc" },
    }),
    prisma.emissionFactor.findMany({ orderBy: { activity: "asc" } }),
    prisma.department.findMany({
      where: { status: "ACTIVE" },
      select: { id: true, name: true, code: true },
    }),
  ]);

  // Aggregate CO2 by department
  const byDept: Record<string, { name: string; co2Kg: number; txCount: number }> = {};
  for (const tx of transactions) {
    const key = tx.department.name;
    if (!byDept[key]) byDept[key] = { name: key, co2Kg: 0, txCount: 0 };
    byDept[key].co2Kg += tx.co2Kg;
    byDept[key].txCount++;
  }

  // Aggregate CO2 by source type
  const bySource: Record<string, number> = {};
  for (const tx of transactions) {
    bySource[tx.sourceType] = (bySource[tx.sourceType] ?? 0) + tx.co2Kg;
  }

  // Monthly trend
  const byMonth: Record<string, number> = {};
  for (const tx of transactions) {
    const key = new Date(tx.date).toLocaleDateString("en-IN", {
      month: "short",
      year: "2-digit",
    });
    byMonth[key] = (byMonth[key] ?? 0) + tx.co2Kg;
  }

  const totalCO2 = transactions.reduce((s, t) => s + t.co2Kg, 0);
  const autoGenCount = transactions.filter((t) => t.autoGenerated).length;

  return {
    transactions,
    goals,
    emissionFactors,
    departments: depts,
    summary: {
      totalCO2Kg: totalCO2,
      autoGeneratedPct: transactions.length > 0
        ? (autoGenCount / transactions.length) * 100
        : 0,
      goalsOnTrackPct:
        goals.length > 0
          ? (goals.filter((g) => g.status === "ON_TRACK" || g.status === "COMPLETED").length /
              goals.length) *
            100
          : 0,
      txCount: transactions.length,
    },
    byDept: Object.values(byDept).sort((a, b) => b.co2Kg - a.co2Kg),
    bySource: Object.entries(bySource).map(([name, co2Kg]) => ({ name, co2Kg })),
    byMonth: Object.entries(byMonth).map(([month, co2Kg]) => ({ month, co2Kg })),
  };
}

export type EnvironmentalReportData = Awaited<
  ReturnType<typeof getEnvironmentalReportData>
>;

// ─── Social Report ────────────────────────────────────────────────────────────

export async function getSocialReportData(filters?: {
  departmentId?: string;
  fromDate?: Date;
  toDate?: Date;
}) {
  await requireAuth();

  const range = dateRange(filters?.fromDate, filters?.toDate);
  const deptFilter = filters?.departmentId
    ? { departmentId: filters.departmentId }
    : {};

  const [activities, training, participations, employees] = await Promise.all([
    prisma.cSRActivity.findMany({
      where: deptFilter,
      include: {
        category: { select: { name: true } },
        department: { select: { name: true } },
        _count: { select: { participations: true } },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.trainingRecord.findMany({
      include: {
        employee: {
          include: {
            department: { select: { name: true } },
          },
        },
      },
    }),
    prisma.employeeParticipation.findMany({
      where: { createdAt: range },
      include: {
        activity: { select: { title: true } },
        employee: {
          include: {
            department: { select: { name: true } },
          },
        },
      },
    }),
    prisma.employee.findMany({
      include: { department: { select: { name: true } } },
    }),
  ]);

  // Gender breakdown
  const genderBreakdown: Record<string, number> = {};
  for (const emp of employees) {
    const g = emp.gender ?? "Unknown";
    genderBreakdown[g] = (genderBreakdown[g] ?? 0) + 1;
  }

  // Participation approval breakdown
  const approvalBreakdown = {
    approved: participations.filter((p) => p.approval === "APPROVED").length,
    pending: participations.filter((p) => p.approval === "PENDING").length,
    rejected: participations.filter((p) => p.approval === "REJECTED").length,
  };
  const total = participations.length;
  const approvalRate = total > 0 ? (approvalBreakdown.approved / total) * 100 : 0;

  // Training completion
  const trainingTotal = training.length;
  const trainingCompleted = training.filter((t) => t.completed).length;
  const trainingRate = trainingTotal > 0 ? (trainingCompleted / trainingTotal) * 100 : 0;

  return {
    activities,
    training,
    participations,
    summary: {
      totalActivities: activities.length,
      totalParticipations: total,
      approvalRate,
      trainingCompletionRate: trainingRate,
      genderBreakdown: Object.entries(genderBreakdown).map(([name, count]) => ({
        name,
        count,
      })),
    },
    approvalBreakdown,
  };
}

export type SocialReportData = Awaited<ReturnType<typeof getSocialReportData>>;

// ─── Governance Report ────────────────────────────────────────────────────────

export async function getGovernanceReportData(filters?: {
  departmentId?: string;
  fromDate?: Date;
  toDate?: Date;
}) {
  await requireAuth();

  const deptFilter = filters?.departmentId
    ? { departmentId: filters.departmentId }
    : {};

  const [policies, audits, complianceIssues, allEmployees] = await Promise.all([
    prisma.eSGPolicy.findMany({
      include: {
        acknowledgements: { select: { acknowledgedAt: true, employeeId: true } },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.audit.findMany({
      where: deptFilter,
      include: {
        department: { select: { name: true } },
        _count: { select: { complianceIssues: true } },
      },
      orderBy: { date: "desc" },
    }),
    prisma.complianceIssue.findMany({
      where: deptFilter,
      include: {
        department: { select: { name: true } },
        audit: { select: { title: true } },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.employee.findMany({ select: { id: true } }),
  ]);

  const empCount = allEmployees.length;

  // Policy acknowledgement rates
  const policyStats = policies.map((p) => ({
    id: p.id,
    title: p.title,
    version: p.version,
    totalEmployees: empCount,
    acknowledged: p.acknowledgements.filter((a) => a.acknowledgedAt !== null).length,
    acknowledgeRate:
      empCount > 0
        ? (p.acknowledgements.filter((a) => a.acknowledgedAt !== null).length /
            empCount) *
          100
        : 0,
  }));

  // Compliance by severity
  const bySeverity: Record<string, number> = {};
  for (const ci of complianceIssues) {
    bySeverity[ci.severity] = (bySeverity[ci.severity] ?? 0) + 1;
  }

  const overdueCount = complianceIssues.filter(
    (ci) => ci.status === "OVERDUE" || (ci.dueDate && new Date(ci.dueDate) < new Date() && ci.status !== "RESOLVED")
  ).length;

  return {
    policies: policyStats,
    audits,
    complianceIssues,
    summary: {
      policyAckRate:
        policyStats.length > 0
          ? policyStats.reduce((s, p) => s + p.acknowledgeRate, 0) / policyStats.length
          : 0,
      openIssues: complianceIssues.filter((ci) => ci.status === "OPEN").length,
      overdueIssues: overdueCount,
      auditsCompleted: audits.filter((a) => a.status === "COMPLETED").length,
      totalAudits: audits.length,
    },
    bySeverity: Object.entries(bySeverity).map(([name, count]) => ({
      name,
      count,
    })),
  };
}

export type GovernanceReportData = Awaited<
  ReturnType<typeof getGovernanceReportData>
>;

// ─── ESG Summary Report ───────────────────────────────────────────────────────

export async function getEsgSummaryData(filters?: {
  departmentId?: string;
}) {
  await requireAuth();

  const deptFilter = filters?.departmentId
    ? { departmentId: filters.departmentId }
    : {};

  const [deptScores, esgConfig, topEmployees, challengeStats] = await Promise.all([
    prisma.departmentScore.findMany({
      where: deptFilter,
      include: { department: true },
      orderBy: { total: "desc" },
    }),
    prisma.eSGConfig.findFirst({ where: { id: "singleton" } }),
    prisma.employee.findMany({
      orderBy: { xp: "desc" },
      take: 5,
      include: { department: { select: { name: true } } },
    }),
    prisma.challenge.findMany({
      where: { status: { in: ["ACTIVE", "COMPLETED"] } },
      include: { _count: { select: { participations: true } } },
    }),
  ]);

  const weights = {
    env: esgConfig?.envWeight ?? 0.4,
    social: esgConfig?.socialWeight ?? 0.3,
    gov: esgConfig?.govWeight ?? 0.3,
  };

  const overallScores = deptScores.map((ds) => ({
    name: ds.department.name,
    code: ds.department.code,
    environmental: ds.environmental,
    social: ds.social,
    governance: ds.governance,
    total: ds.total,
    isFallback: ds.isFallback,
  }));

  const avgEnv =
    overallScores.length > 0
      ? overallScores.reduce((s, d) => s + d.environmental, 0) / overallScores.length
      : 0;
  const avgSocial =
    overallScores.length > 0
      ? overallScores.reduce((s, d) => s + d.social, 0) / overallScores.length
      : 0;
  const avgGov =
    overallScores.length > 0
      ? overallScores.reduce((s, d) => s + d.governance, 0) / overallScores.length
      : 0;
  const avgTotal = avgEnv * weights.env + avgSocial * weights.social + avgGov * weights.gov;

  return {
    deptScores: overallScores,
    weights,
    summary: {
      overallESGScore: Math.round(avgTotal),
      envScore: Math.round(avgEnv),
      socialScore: Math.round(avgSocial),
      govScore: Math.round(avgGov),
      topDept: overallScores[0] ?? null,
      bottomDept: overallScores[overallScores.length - 1] ?? null,
    },
    topEmployees,
    challengeStats: {
      active: challengeStats.filter((c) => c.status === "ACTIVE").length,
      totalParticipations: challengeStats.reduce(
        (s, c) => s + c._count.participations,
        0
      ),
    },
    radarData: overallScores.map((d) => ({
      dept: d.code,
      Environmental: d.environmental,
      Social: d.social,
      Governance: d.governance,
    })),
  };
}

export type EsgSummaryData = Awaited<ReturnType<typeof getEsgSummaryData>>;

// ─── Custom Report ────────────────────────────────────────────────────────────

export async function getCustomReportData(filters: CustomReportFilters) {
  await requireAuth();

  const results: Record<string, unknown> = {};

  if (!filters.module || filters.module === "environmental") {
    results.environmental = await getEnvironmentalReportData({
      departmentId: filters.departmentId,
      fromDate: filters.fromDate,
      toDate: filters.toDate,
    });
  }

  if (!filters.module || filters.module === "social") {
    results.social = await getSocialReportData({
      departmentId: filters.departmentId,
      fromDate: filters.fromDate,
      toDate: filters.toDate,
    });
  }

  if (!filters.module || filters.module === "governance") {
    results.governance = await getGovernanceReportData({
      departmentId: filters.departmentId,
      fromDate: filters.fromDate,
      toDate: filters.toDate,
    });
  }

  if (!filters.module || filters.module === "gamification") {
    results.gamification = await getEsgSummaryData({
      departmentId: filters.departmentId,
    });
  }

  return results;
}
